// Copyright (c) Microsoft Corporation. All rights reserved.
// SPDX-License-Identifier: MIT

// Wifi
#define IOT_CONFIG_WIFI_SSID "SSID_WIFI"
#define IOT_CONFIG_WIFI_PASSWORD "SENHA"
// Enable macro IOT_CONFIG_USE_X509_CERT to use an x509 certificate to authenticate the IoT device.
// The two main modes of authentication are through SAS tokens (automatically generated by the
// sample using the provided device symmetric key) or through x509 certificates. Please choose the
// appropriate option according to your device authentication mode.

#define IOT_CONFIG_USE_X509_CERT

#ifdef IOT_CONFIG_USE_X509_CERT

/*
 * Please set the define IOT_CONFIG_DEVICE_CERT below with
 * the content of your device x509 certificate.
 *
 * Example:
 * #define IOT_CONFIG_DEVICE_CERT "-----BEGIN CERTIFICATE-----\n" \
 * "MIIBJDCBywIUfeHrebBVa2eZAbouBgACp9R3BncwCgYIKoZIzj0EAwIwETEPMA0G\n" \
 * "A1UEAwwGRFBTIENBMB4XDTIyMDMyMjazMTAzN1oXDTIzMDMyMjIzMTAzN1owGTEX\n" \
 * "MBUGA1UEAwwOY29udG9zby1kZXZpY2UwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNC\n" \
 * .......
 * "YmGzdaHTb6P1W+p+jmc+jJn1MAoGCXqGSM49BAMCA0gAMEUCIEnbEMsAdGFroMwl\n" \
 * "vTfQahwsxN3xink9z1gtirrjQlqDAiEAyU+6TUJcG6d9JF+uJqsLFpsbbF3IzGAw\n" \
 * "yC+koNRC0MU=\n" \
 * "-----END CERTIFICATE-----"
 *
 */

#define IOT_CONFIG_DEVICE_CERT "-----BEGIN CERTIFICATE-----""\n" \
"MIIFezCCA2OgAwIBAgIQLg92GR5MKUwRYpRIDpVcgzANBgkqhkiG9w0BAQsFADA0""\n" \
/* ATUALIZAR COM A CORRENTE DE CERTIFICADO DO DISPOSITIVO COMPLETA */
"PjhlWngC2vT7rvwfPWbVJS2bgO2AVAb1jP+/gLGremvzpGXT3sPNq/eO6XS9fnW8""\n" \
"3TQaG01veaRX""\n" \
"-----END CERTIFICATE-----";



//#define IOT_CONFIG_DEVICE_CERT "Device Certificate"

/*
 * Please set the define IOT_CONFIG_DEVICE_CERT_PRIVATE_KEY below with
 * the content of your device x509 private key.
 *
 * Example:
 *
 * #define IOT_CONFIG_DEVICE_CERT_PRIVATE_KEY "-----BEGIN EC PRIVATE KEY-----\n" \
 * "MHcCAQEEIKGXkMMiO9D7jYpUjUGTBn7gGzeKPeNzCP83wbfQfLd9obAoGCCqGSM49\n" \
 * "AwEHoUQDQgAEU6nQoYbjgJvBwaeD6MyAYmOSDg0QhEdyyV337qrlIbDEKvFsn1El\n" \
 * "yRabc4dNp2Jhs3Xh02+j9Vvqfo5nPoyZ9Q==\n" \
 * "-----END EC PRIVATE KEY-----"
 *
 * Note the type of key may different in your case. Such as BEGIN PRIVATE KEY
 * or BEGIN RSA PRIVATE KEY.
 *
 */
 
#define IOT_CONFIG_DEVICE_CERT_PRIVATE_KEY "-----BEGIN RSA PRIVATE KEY-----""\n" \
"MIIJKQIBAAKCAgEA34VqbuH9YEte8Q0INXOhZ2yk4mu++Pc3s43CMViG3jp917za""\n" \
/* ATUALIZAR COM A CHAVE PRIVADA DO CERTIFICADO DO DISPOSITIVO */
"XnbD4FlI0vlT8WYlvr/+pwGTM2BbTV1VCD3KrWZeql7Bji8D2gvZWCX0vHvs""\n" \
"-----END RSA PRIVATE KEY-----";

#endif // IOT_CONFIG_USE_X509_CERT



// Azure IoT
#define IOT_CONFIG_IOTHUB_FQDN "mqtts://[your Azure IoT host name].azure-devices.net"
#define IOT_CONFIG_DPS_FQDN "mqtts://global.azure-devices-provisioning.net"

#define IOT_CONFIG_DPS_SCOPE "<SCOPE ID DO DPS>"
#define IOT_CONFIG_DPS_REGISTRATION_ID "<DEVICE ID CONTIDO NO CERTIFICADO>"
#define IOT_CONFIG_DEVICE_ID "<DEVICE ID CONTIDO NO CERTIFICADO>"
// Use device key if not using certificates
#ifndef IOT_CONFIG_USE_X509_CERT
#define IOT_CONFIG_DEVICE_KEY "Device Key"
#endif // IOT_CONFIG_USE_X509_CERT

// Publish 1 message every 2 seconds
#define TELEMETRY_FREQUENCY_MILLISECS 2000
//#define MBEDTLS_SSL_IN_CONTENT_LEN 4096
//#define MBEDTLS_SSL_MAX_CONTENT_LEN 4096

//#define MBEDTLS_SSL_PROTO_TLS1_2
